CREATE TABLE IF NOT EXISTS cards (
	id TEXT NOT NULL PRIMARY KEY,
	board TEXT NOT NULL,
	type TEXT NOT NULL,
	x NUMBER NOT NULL,
	y NUMBER NOT NULL,
	content JSON NOT NULL,
	created DATETIME NOT NULL,
	modified DATETIME NOT NULL,
	FOREIGN KEY (board) REFERENCES boards (id) ON DELETE CASCADE
);
