// Fix omitted .js extensions in imports generated by TypeScript
// @ts-nocheck

export function resolve(specifier, context, nextResolve) {
	if (specifier.startsWith('./') || specifier.startsWith('../')) {
		if (!(specifier.endsWith('.js') || specifier.endsWith('.mjs') || specifier.endsWith('.cjs')
		))
			return nextResolve(`${specifier}.js`, context)
	}

	return nextResolve(specifier, context)
}
